# Generated by Django 4.1.2 on 2022-10-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perseverance', models.CharField(max_length=500)),
                ('relationship', models.CharField(max_length=500)),
                ('discipline', models.CharField(max_length=500)),
                ('accountability', models.CharField(max_length=500)),
                ('generosity_humility', models.CharField(max_length=500)),
                ('general', models.CharField(max_length=500)),
            ],
        ),
    ]
