# Generated by Django 4.1.2 on 2022-10-14 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.CharField(max_length=5000)),
                ('date', models.DateField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=75)),
                ('quote_source', models.CharField(max_length=100)),
                ('philosophile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
